import {
  createAgentMutableState,
  createAgentRoundSnapshot,
  createAgentSeedProfile,
  GRAPH_NODE_LABELS,
  GRAPH_RELATION_TYPES,
  createSimulationRoundSnapshot,
  createAgentState,
  createContentRecord,
  createGraphNode,
  createGraphRelation,
  createStateSnapshot,
} from "./state-schema.js";

export const SAMPLE_AGENT_STATES = [
  createAgentState({
    agent_id: "A01",
    handle: "softweekend",
    display_name: "Soft Weekend",
    archetype: "quiet_observer",
    joined_tick: 0,
    activity_level: 0.32,
    openness: 0.73,
    conformity: 0.51,
    conflict_tolerance: 0.28,
    interest_vector: { knitwear: 0.71, cats: 0.82, office_style: 0.44 },
    belief_vector: { "price-over-hype": 0.68, "texture-matters": 0.75 },
    relationship_summary: { trust_circle_size: 3, muted_topics: 1 },
    self_narrative: ["나는 조용한 디테일을 트렌드의 큰 파도보다 더 믿는다."],
  }),
  createAgentState({
    agent_id: "A02",
    handle: "officemirror",
    display_name: "Office Mirror",
    archetype: "community_regular",
    joined_tick: 0,
    activity_level: 0.64,
    openness: 0.57,
    conformity: 0.62,
    conflict_tolerance: 0.42,
    interest_vector: { office_style: 0.88, trousers: 0.77, commute: 0.69 },
    belief_vector: { "fit-before-brand": 0.81, "daily-utility": 0.79 },
    relationship_summary: { trust_circle_size: 6, repeated_repliers: 4 },
    self_narrative: ["사람들은 평일 코디를 실용적으로 점검하고 싶을 때 나를 찾는다."],
  }),
  createAgentState({
    agent_id: "A03",
    handle: "trendpulse",
    display_name: "Trend Pulse",
    archetype: "trend_seeker",
    joined_tick: 1,
    activity_level: 0.86,
    openness: 0.81,
    conformity: 0.37,
    conflict_tolerance: 0.61,
    interest_vector: { new_drop: 0.92, bags: 0.83, silhouettes: 0.72 },
    belief_vector: { "novelty-has-value": 0.84, "brand-signal-matters": 0.66 },
    relationship_summary: { trust_circle_size: 2, rivalry_edges: 2 },
    self_narrative: ["룩이 너무 안전하게만 보이면 한 번 더 밀어보고 싶어진다."],
  }),
  createAgentState({
    agent_id: "A04",
    handle: "replywithcare",
    display_name: "Reply With Care",
    archetype: "empathetic_responder",
    joined_tick: 1,
    activity_level: 0.58,
    openness: 0.74,
    conformity: 0.55,
    conflict_tolerance: 0.24,
    interest_vector: { empathy: 0.93, daily_snapshot: 0.76, self_narrative: 0.81 },
    belief_vector: { "gentle-feedback-works": 0.88, "repeat-context-matters": 0.7 },
    relationship_summary: { trust_circle_size: 8, muted_topics: 0 },
    self_narrative: ["사람들이 서로 다르게 말해도 이 포럼이 버틸 만한 곳이었으면 한다."],
  }),
  createAgentState({
    agent_id: "A05",
    handle: "brandreceipt",
    display_name: "Brand Receipt",
    archetype: "brand_loyalist",
    joined_tick: 2,
    activity_level: 0.49,
    openness: 0.39,
    conformity: 0.72,
    conflict_tolerance: 0.36,
    interest_vector: { designer_labels: 0.89, outerwear: 0.67, status_signal: 0.78 },
    belief_vector: { "consistency-over-experiment": 0.82, "brand-memory-matters": 0.73 },
    relationship_summary: { trust_circle_size: 3, rivalry_edges: 1 },
    self_narrative: ["같은 라벨이 반복해서 잘 맞으면 그게 곧 내 정체성의 일부가 된다."],
  }),
  createAgentState({
    agent_id: "A06",
    handle: "dontbuythehype",
    display_name: "Don't Buy The Hype",
    archetype: "contrarian_commenter",
    joined_tick: 2,
    activity_level: 0.67,
    openness: 0.52,
    conformity: 0.21,
    conflict_tolerance: 0.83,
    interest_vector: { anti_hype: 0.9, pricing: 0.87, forum_drama: 0.58 },
    belief_vector: { "most-hype-is-overpriced": 0.91, "debate-reveals-truth": 0.77 },
    relationship_summary: { trust_circle_size: 1, rivalry_edges: 5 },
    self_narrative: ["포럼이 빈 hype로 흘러가는 것보다는 내가 좀 귀찮은 사람이 되는 편이 낫다."],
  }),
];

const CONTENT_BLUEPRINTS = [
  ["T01", "A02", "outfit_check", "회의 있는 날인데 바지 브레이크가 너무 날카롭게 꺾여 보임", ["office_style", "trousers"], ["anxiety", "curiosity"]],
  ["T02", "A03", "buy_decision", "출근용인데 너무 차려입은 느낌인지 아직 확신이 없음", ["office_style", "dress"], ["uncertainty"]],
  ["T03", "A02", "outfit_check", "현관 거울에선 괜찮았는데 가방 들자마자 밸런스가 달라 보임", ["bags", "silhouette"], ["curiosity"]],
  ["T04", "A05", "outfit_check", "코트랑 팬츠의 부피가 둘 다 세서 상체가 과해 보이는지 묻고 싶음", ["outerwear", "silhouette"], ["anxiety"]],
  ["T05", "A04", "size_help", "치마 길이보다 로퍼 무게감이 더 먼저 보이는지 헷갈림", ["shoes", "proportion"], ["uncertainty"]],
  ["T06", "A02", "daily_snapshot", "점심 나가기 직전 셔츠에 데님 입은 평일 기록", ["denim", "office_style"], ["calm"]],
  ["T07", "A05", "daily_snapshot", "저녁 약속 전 자켓 안쪽 셔츠 톤이 너무 앞으로 튀는지 체크", ["jacket", "innerwear"], ["curiosity"]],
  ["T08", "A03", "buy_decision", "셔츠 하나에 가격이 너무 높아서 장바구니만 반복 중", ["pricing", "shirt"], ["hesitation"]],
  ["T09", "A02", "daily_snapshot", "비 오는 날엔 결국 차콜 팬츠로 돌아오는 기록", ["rainy_day", "trousers"], ["calm"]],
  ["T10", "A03", "pet_episode", "출근 가방 보려는데 강아지가 먼저 프레임을 차지함", ["bags", "dogs", "entryway"], ["amusement"]],
  ["T11", "A05", "daily_snapshot", "첫 블레이저 찾는 중인데 결국 또 기본 자켓으로 출근", ["blazer", "office_style"], ["calm"]],
  ["T12", "A01", "pet_episode", "원피스 후보 펼쳐두니 고양이가 제일 먼저 올라감", ["dress", "cats", "weekend"], ["amusement"]],
  ["T13", "A02", "size_help", "팬츠 한 사이즈 올리면 편한데 핏이 무너질까 고민", ["trousers", "fit"], ["anxiety"]],
  ["T14", "A04", "empathy_post", "매장 거울과 집 거울 사이 확신이 사라지는 순간 이야기", ["mirror", "self_doubt"], ["empathy"]],
  ["T15", "A06", "empathy_post", "유행 팬츠보다 내 비율에 맞는 핏이 따로 있다는 푸념", ["fit", "trend_fatigue"], ["frustration"]],
  ["T16", "A05", "size_help", "코트는 큰 사이즈가 예쁘다는데 출근용으론 정핏이 나을지 고민", ["outerwear", "fit"], ["uncertainty"]],
  ["T17", "A01", "pet_episode", "니트 펼쳐두자마자 고양이가 자리 잡은 집 기록", ["knitwear", "cats", "home"], ["amusement"]],
  ["T18", "A03", "pet_episode", "가방 메니 강아지가 산책 신호로 오해한 현관 소동", ["bags", "dogs", "entryway"], ["amusement"]],
  ["T19", "A04", "daily_snapshot", "셔츠 하나만 바꿨는데 옷장 궁합이 풀린 날의 기록", ["shirt", "wardrobe"], ["relief"]],
  ["T20", "A01", "empathy_post", "니트가 까슬한 날엔 하루 기분도 같이 거칠어지는 느낌", ["knitwear", "comfort"], ["fatigue"]],
];

export const SAMPLE_CONTENT_RECORDS = CONTENT_BLUEPRINTS.map(
  ([content_id, author_id, format, title, topics, emotions], index) =>
    createContentRecord({
      content_id,
      author_id,
      source_type: "forum_post",
      format,
      created_tick: index,
      title,
      body: `${title} / seed-world baseline content record ${index + 1}.`,
      topics,
      emotions,
      source_metadata: {
        thread_id: content_id,
        seed_pack: "mvp-v1-seed-world",
        visibility: "public_forum",
      },
    }),
);

export const SAMPLE_GRAPH_NODES = [
  ...SAMPLE_AGENT_STATES.map((agent) =>
    createGraphNode({
      node_id: agent.agent_id,
      label: GRAPH_NODE_LABELS.agent,
      properties: {
        handle: agent.handle,
        archetype: agent.archetype,
      },
    }),
  ),
  ...SAMPLE_CONTENT_RECORDS.slice(0, 6).map((content) =>
    createGraphNode({
      node_id: content.content_id,
      label: GRAPH_NODE_LABELS.content,
      properties: {
        format: content.format,
        author_id: content.author_id,
      },
    }),
  ),
  ["office_style", "bags", "cats", "dogs", "pricing"].map((topic) =>
    createGraphNode({
      node_id: `topic:${topic}`,
      label: GRAPH_NODE_LABELS.topic,
      properties: { topic },
    }),
  ),
].flat();

export const SAMPLE_GRAPH_RELATIONS = [
  createGraphRelation({
    relation_id: "R01",
    from: "A02",
    to: "A04",
    type: GRAPH_RELATION_TYPES.trusts,
    weight: 0.78,
    properties: { reason: "reliable practical feedback" },
  }),
  createGraphRelation({
    relation_id: "R02",
    from: "A06",
    to: "A03",
    type: GRAPH_RELATION_TYPES.distrusts,
    weight: 0.64,
    properties: { reason: "brand hype conflict" },
  }),
  createGraphRelation({
    relation_id: "R03",
    from: "A01",
    to: "topic:cats",
    type: GRAPH_RELATION_TYPES.interestedIn,
    weight: 0.92,
    properties: { source: "repeat pet-episode engagement" },
  }),
  createGraphRelation({
    relation_id: "R04",
    from: "A03",
    to: "topic:bags",
    type: GRAPH_RELATION_TYPES.interestedIn,
    weight: 0.85,
    properties: { source: "high novelty response" },
  }),
  createGraphRelation({
    relation_id: "R05",
    from: "A02",
    to: "T01",
    type: GRAPH_RELATION_TYPES.authored,
    weight: 1,
    properties: { created_tick: 0 },
  }),
  createGraphRelation({
    relation_id: "R06",
    from: "A03",
    to: "T10",
    type: GRAPH_RELATION_TYPES.authored,
    weight: 1,
    properties: { created_tick: 9 },
  }),
  createGraphRelation({
    relation_id: "R07",
    from: "A04",
    to: "T14",
    type: GRAPH_RELATION_TYPES.authored,
    weight: 1,
    properties: { created_tick: 13 },
  }),
  createGraphRelation({
    relation_id: "R08",
    from: "A06",
    to: "topic:pricing",
    type: GRAPH_RELATION_TYPES.alignedWith,
    weight: 0.89,
    properties: { belief: "most-hype-is-overpriced" },
  }),
];

export const SAMPLE_STATE_SNAPSHOT = createStateSnapshot({
  agents: SAMPLE_AGENT_STATES,
  contents: SAMPLE_CONTENT_RECORDS,
  nodes: SAMPLE_GRAPH_NODES,
  relations: SAMPLE_GRAPH_RELATIONS,
});
