import {
  createAgentMutableState,
  createAgentRoundSnapshot,
  createAgentSeedProfile,
  GRAPH_NODE_LABELS,
  GRAPH_RELATION_TYPES,
  createSimulationRoundSnapshot,
  createAgentState,
  createContentRecord,
  createGraphNode,
  createGraphRelation,
  createStateSnapshot,
} from "./state-schema.js";

export const SAMPLE_AGENT_STATES = [
  createAgentState({
    agent_id: "A01",
    handle: "softweekend",
    display_name: "Soft Weekend",
    archetype: "quiet_observer",
    joined_tick: 0,
    activity_level: 0.32,
    openness: 0.73,
    conformity: 0.51,
    conflict_tolerance: 0.28,
    interest_vector: { knitwear: 0.71, cats: 0.82, office_style: 0.44 },
    belief_vector: { "price-over-hype": 0.68, "texture-matters": 0.75 },
    relationship_summary: { trust_circle_size: 3, muted_topics: 1 },
    self_narrative: ["I trust quiet details more than trend spikes."],
  }),
  createAgentState({
    agent_id: "A02",
    handle: "officemirror",
    display_name: "Office Mirror",
    archetype: "community_regular",
    joined_tick: 0,
    activity_level: 0.64,
    openness: 0.57,
    conformity: 0.62,
    conflict_tolerance: 0.42,
    interest_vector: { office_style: 0.88, trousers: 0.77, commute: 0.69 },
    belief_vector: { "fit-before-brand": 0.81, "daily-utility": 0.79 },
    relationship_summary: { trust_circle_size: 6, repeated_repliers: 4 },
    self_narrative: ["People come to me when they want practical weekday feedback."],
  }),
  createAgentState({
    agent_id: "A03",
    handle: "trendpulse",
    display_name: "Trend Pulse",
    archetype: "trend_seeker",
    joined_tick: 1,
    activity_level: 0.86,
    openness: 0.81,
    conformity: 0.37,
    conflict_tolerance: 0.61,
    interest_vector: { new_drop: 0.92, bags: 0.83, silhouettes: 0.72 },
    belief_vector: { "novelty-has-value": 0.84, "brand-signal-matters": 0.66 },
    relationship_summary: { trust_circle_size: 2, rivalry_edges: 2 },
    self_narrative: ["If a look feels too safe, I want to push it."],
  }),
  createAgentState({
    agent_id: "A04",
    handle: "replywithcare",
    display_name: "Reply With Care",
    archetype: "empathetic_responder",
    joined_tick: 1,
    activity_level: 0.58,
    openness: 0.74,
    conformity: 0.55,
    conflict_tolerance: 0.24,
    interest_vector: { empathy: 0.93, daily_snapshot: 0.76, self_narrative: 0.81 },
    belief_vector: { "gentle-feedback-works": 0.88, "repeat-context-matters": 0.7 },
    relationship_summary: { trust_circle_size: 8, muted_topics: 0 },
    self_narrative: ["I want the forum to feel survivable even when people disagree."],
  }),
  createAgentState({
    agent_id: "A05",
    handle: "brandreceipt",
    display_name: "Brand Receipt",
    archetype: "brand_loyalist",
    joined_tick: 2,
    activity_level: 0.49,
    openness: 0.39,
    conformity: 0.72,
    conflict_tolerance: 0.36,
    interest_vector: { designer_labels: 0.89, outerwear: 0.67, status_signal: 0.78 },
    belief_vector: { "consistency-over-experiment": 0.82, "brand-memory-matters": 0.73 },
    relationship_summary: { trust_circle_size: 3, rivalry_edges: 1 },
    self_narrative: ["If a label repeatedly works for me, that becomes part of my identity."],
  }),
  createAgentState({
    agent_id: "A06",
    handle: "dontbuythehype",
    display_name: "Don't Buy The Hype",
    archetype: "contrarian_commenter",
    joined_tick: 2,
    activity_level: 0.67,
    openness: 0.52,
    conformity: 0.21,
    conflict_tolerance: 0.83,
    interest_vector: { anti_hype: 0.9, pricing: 0.87, forum_drama: 0.58 },
    belief_vector: { "most-hype-is-overpriced": 0.91, "debate-reveals-truth": 0.77 },
    relationship_summary: { trust_circle_size: 1, rivalry_edges: 5 },
    self_narrative: ["I would rather be annoying than let the forum drift into empty hype."],
  }),
];

export const SPRINT1_AGENT_STATES = [
  createAgentState({
    agent_id: "S01",
    handle: "quietsignal",
    display_name: "Quiet Signal",
    archetype: "quiet_observer",
    joined_tick: 0,
    activity_level: 0.24,
    openness: 0.72,
    conformity: 0.43,
    conflict_tolerance: 0.22,
    interest_vector: { care: 0.58, texture: 0.66, daily_life: 0.62 },
    belief_vector: { "small-details-carry-meaning": 0.63 },
    relationship_summary: { trust_circle_size: 1, repeated_repliers: 0 },
    self_narrative: ["I notice the mood under a post before I react to it."],
    seed_profile: createAgentSeedProfile({
      seed_id: "seed-quietsignal",
      archetype_hint: "quiet_observer",
      baseline_traits: {
        curiosity: 0.61,
        status_drive: 0.22,
        care_drive: 0.77,
        novelty_drive: 0.34,
        skepticism: 0.41,
        belonging_drive: 0.55,
      },
      interest_seeds: {
        lived_context: 0.72,
        care_topics: 0.69,
        style_signal: 0.43,
      },
      value_seeds: {
        "care-over-performance": 0.75,
        "texture-matters": 0.7,
      },
      emotional_bias: {
        empathy: 0.78,
        discomfort_with_hype: 0.36,
      },
      voice_notes: [
        "starts observant rather than declarative",
        "needs repeated evidence before strong public stance",
      ],
    }),
    mutable_state: createAgentMutableState({
      current_traits: {
        curiosity: 0.61,
        status_drive: 0.22,
        care_drive: 0.77,
        novelty_drive: 0.34,
        skepticism: 0.41,
        belonging_drive: 0.55,
      },
      current_interests: {
        lived_context: 0.72,
        care_topics: 0.69,
        style_signal: 0.43,
      },
      current_beliefs: {
        "care-over-performance": 0.75,
        "texture-matters": 0.7,
      },
      attention_bias: {
        rescue_stories: 0.61,
        quiet_forum_posts: 0.57,
      },
      affect_state: {
        empathy: 0.78,
        irritation: 0.18,
      },
      self_narrative_summary: "Still mostly observant, but increasingly moved by care-oriented stories.",
      recent_arc: "softening_toward_care_topics",
      stance_markers: ["care-first", "quiet-reader"],
      drift_log: ["tick-2: stronger emotional response to care-heavy content"],
    }),
  }),
  createAgentState({
    agent_id: "S02",
    handle: "signaldrift",
    display_name: "Signal Drift",
    archetype: "trend_seeker",
    joined_tick: 0,
    activity_level: 0.56,
    openness: 0.81,
    conformity: 0.28,
    conflict_tolerance: 0.53,
    interest_vector: { novelty: 0.84, aesthetics: 0.78, status_signal: 0.66 },
    belief_vector: { "novelty-has-value": 0.82 },
    relationship_summary: { trust_circle_size: 1, rivalry_edges: 1 },
    self_narrative: ["If everyone already agrees, I want the next signal."],
    seed_profile: createAgentSeedProfile({
      seed_id: "seed-signaldrift",
      archetype_hint: "trend_seeker",
      baseline_traits: {
        curiosity: 0.79,
        status_drive: 0.63,
        care_drive: 0.28,
        novelty_drive: 0.86,
        skepticism: 0.35,
        belonging_drive: 0.31,
      },
      interest_seeds: {
        trend_objects: 0.87,
        aesthetic_discourse: 0.74,
        brand_signal: 0.69,
      },
      value_seeds: {
        "novelty-has-value": 0.82,
        "signal-before-consensus": 0.71,
      },
      emotional_bias: {
        excitement: 0.84,
        boredom_with_safe_opinions: 0.76,
      },
      voice_notes: [
        "moves early toward novelty clusters",
        "reacts strongly when a forum feels stale",
      ],
    }),
    mutable_state: createAgentMutableState({
      current_traits: {
        curiosity: 0.79,
        status_drive: 0.63,
        care_drive: 0.28,
        novelty_drive: 0.86,
        skepticism: 0.35,
        belonging_drive: 0.31,
      },
      current_interests: {
        trend_objects: 0.87,
        aesthetic_discourse: 0.74,
        brand_signal: 0.69,
      },
      current_beliefs: {
        "novelty-has-value": 0.82,
        "signal-before-consensus": 0.71,
      },
      attention_bias: {
        early_adopter_posts: 0.77,
        visual_novelty: 0.81,
      },
      affect_state: {
        excitement: 0.84,
        annoyance: 0.29,
      },
      self_narrative_summary: "Still chasing novelty, but starting to frame it as identity rather than taste.",
      recent_arc: "reinforcing_novelty_identity",
      stance_markers: ["anti-stagnation", "signal-seeking"],
      drift_log: ["tick-2: repeated novelty content hardened anti-safe posture"],
    }),
  }),
  createAgentState({
    agent_id: "S03",
    handle: "receiptkeeper",
    display_name: "Receipt Keeper",
    archetype: "contrarian_commenter",
    joined_tick: 0,
    activity_level: 0.62,
    openness: 0.48,
    conformity: 0.19,
    conflict_tolerance: 0.79,
    interest_vector: { pricing: 0.81, fairness: 0.73, callout_energy: 0.68 },
    belief_vector: { "hype-obscures-tradeoffs": 0.86 },
    relationship_summary: { trust_circle_size: 0, rivalry_edges: 2 },
    self_narrative: ["If nobody says the uncomfortable part out loud, I will."],
    seed_profile: createAgentSeedProfile({
      seed_id: "seed-receiptkeeper",
      archetype_hint: "contrarian_commenter",
      baseline_traits: {
        curiosity: 0.52,
        status_drive: 0.34,
        care_drive: 0.37,
        novelty_drive: 0.29,
        skepticism: 0.88,
        belonging_drive: 0.18,
      },
      interest_seeds: {
        pricing: 0.81,
        tradeoff_discourse: 0.75,
        contradiction_spots: 0.72,
      },
      value_seeds: {
        "hype-obscures-tradeoffs": 0.86,
        "debate-reveals-truth": 0.73,
      },
      emotional_bias: {
        irritation_with_consensus: 0.81,
        satisfaction_from_callouts: 0.67,
      },
      voice_notes: [
        "starts skeptical with low group belonging pressure",
        "becomes louder when consensus forms too quickly",
      ],
    }),
    mutable_state: createAgentMutableState({
      current_traits: {
        curiosity: 0.52,
        status_drive: 0.34,
        care_drive: 0.37,
        novelty_drive: 0.29,
        skepticism: 0.88,
        belonging_drive: 0.18,
      },
      current_interests: {
        pricing: 0.81,
        tradeoff_discourse: 0.75,
        contradiction_spots: 0.72,
      },
      current_beliefs: {
        "hype-obscures-tradeoffs": 0.86,
        "debate-reveals-truth": 0.73,
      },
      attention_bias: {
        overhyped_threads: 0.83,
        disagreement_clusters: 0.69,
      },
      affect_state: {
        irritation: 0.72,
        certainty: 0.77,
      },
      self_narrative_summary: "Increasingly sees disagreement as duty, not just preference.",
      recent_arc: "hardening_contrarian_posture",
      stance_markers: ["anti-hype", "tradeoff-first"],
      drift_log: ["tick-2: backlash against celebratory content strengthened callout stance"],
    }),
  }),
];

const CONTENT_BLUEPRINTS = [
  ["T01", "A02", "outfit_check", "회의 있는 날인데 바지 브레이크가 너무 날카롭게 꺾여 보임", ["office_style", "trousers"], ["anxiety", "curiosity"]],
  ["T02", "A03", "buy_decision", "출근용인데 너무 차려입은 느낌인지 아직 확신이 없음", ["office_style", "dress"], ["uncertainty"]],
  ["T03", "A02", "outfit_check", "현관 거울에선 괜찮았는데 가방 들자마자 밸런스가 달라 보임", ["bags", "silhouette"], ["curiosity"]],
  ["T04", "A05", "outfit_check", "코트랑 팬츠의 부피가 둘 다 세서 상체가 과해 보이는지 묻고 싶음", ["outerwear", "silhouette"], ["anxiety"]],
  ["T05", "A04", "size_help", "치마 길이보다 로퍼 무게감이 더 먼저 보이는지 헷갈림", ["shoes", "proportion"], ["uncertainty"]],
  ["T06", "A02", "daily_snapshot", "점심 나가기 직전 셔츠에 데님 입은 평일 기록", ["denim", "office_style"], ["calm"]],
  ["T07", "A05", "daily_snapshot", "저녁 약속 전 자켓 안쪽 셔츠 톤이 너무 앞으로 튀는지 체크", ["jacket", "innerwear"], ["curiosity"]],
  ["T08", "A03", "buy_decision", "셔츠 하나에 가격이 너무 높아서 장바구니만 반복 중", ["pricing", "shirt"], ["hesitation"]],
  ["T09", "A02", "daily_snapshot", "비 오는 날엔 결국 차콜 팬츠로 돌아오는 기록", ["rainy_day", "trousers"], ["calm"]],
  ["T10", "A03", "pet_episode", "출근 가방 보려는데 강아지가 먼저 프레임을 차지함", ["bags", "dogs", "entryway"], ["amusement"]],
  ["T11", "A05", "daily_snapshot", "첫 블레이저 찾는 중인데 결국 또 기본 자켓으로 출근", ["blazer", "office_style"], ["calm"]],
  ["T12", "A01", "pet_episode", "원피스 후보 펼쳐두니 고양이가 제일 먼저 올라감", ["dress", "cats", "weekend"], ["amusement"]],
  ["T13", "A02", "size_help", "팬츠 한 사이즈 올리면 편한데 핏이 무너질까 고민", ["trousers", "fit"], ["anxiety"]],
  ["T14", "A04", "empathy_post", "매장 거울과 집 거울 사이 확신이 사라지는 순간 이야기", ["mirror", "self_doubt"], ["empathy"]],
  ["T15", "A06", "empathy_post", "유행 팬츠보다 내 비율에 맞는 핏이 따로 있다는 푸념", ["fit", "trend_fatigue"], ["frustration"]],
  ["T16", "A05", "size_help", "코트는 큰 사이즈가 예쁘다는데 출근용으론 정핏이 나을지 고민", ["outerwear", "fit"], ["uncertainty"]],
  ["T17", "A01", "pet_episode", "니트 펼쳐두자마자 고양이가 자리 잡은 집 기록", ["knitwear", "cats", "home"], ["amusement"]],
  ["T18", "A03", "pet_episode", "가방 메니 강아지가 산책 신호로 오해한 현관 소동", ["bags", "dogs", "entryway"], ["amusement"]],
  ["T19", "A04", "daily_snapshot", "셔츠 하나만 바꿨는데 옷장 궁합이 풀린 날의 기록", ["shirt", "wardrobe"], ["relief"]],
  ["T20", "A01", "empathy_post", "니트가 까슬한 날엔 하루 기분도 같이 거칠어지는 느낌", ["knitwear", "comfort"], ["fatigue"]],
];

export const SAMPLE_CONTENT_RECORDS = CONTENT_BLUEPRINTS.map(
  ([content_id, author_id, format, title, topics, emotions], index) =>
    createContentRecord({
      content_id,
      author_id,
      source_type: "forum_post",
      format,
      created_tick: index,
      title,
      body: `${title} / seed-world baseline content record ${index + 1}.`,
      topics,
      emotions,
      source_metadata: {
        thread_id: content_id,
        seed_pack: "mvp-v1-seed-world",
        visibility: "public_forum",
      },
    }),
);

export const SAMPLE_GRAPH_NODES = [
  ...SAMPLE_AGENT_STATES.map((agent) =>
    createGraphNode({
      node_id: agent.agent_id,
      label: GRAPH_NODE_LABELS.agent,
      properties: {
        handle: agent.handle,
        archetype: agent.archetype,
      },
    }),
  ),
  ...SAMPLE_CONTENT_RECORDS.slice(0, 6).map((content) =>
    createGraphNode({
      node_id: content.content_id,
      label: GRAPH_NODE_LABELS.content,
      properties: {
        format: content.format,
        author_id: content.author_id,
      },
    }),
  ),
  ["office_style", "bags", "cats", "dogs", "pricing"].map((topic) =>
    createGraphNode({
      node_id: `topic:${topic}`,
      label: GRAPH_NODE_LABELS.topic,
      properties: { topic },
    }),
  ),
].flat();

export const SAMPLE_GRAPH_RELATIONS = [
  createGraphRelation({
    relation_id: "R01",
    from: "A02",
    to: "A04",
    type: GRAPH_RELATION_TYPES.trusts,
    weight: 0.78,
    properties: { reason: "reliable practical feedback" },
  }),
  createGraphRelation({
    relation_id: "R02",
    from: "A06",
    to: "A03",
    type: GRAPH_RELATION_TYPES.distrusts,
    weight: 0.64,
    properties: { reason: "brand hype conflict" },
  }),
  createGraphRelation({
    relation_id: "R03",
    from: "A01",
    to: "topic:cats",
    type: GRAPH_RELATION_TYPES.interestedIn,
    weight: 0.92,
    properties: { source: "repeat pet-episode engagement" },
  }),
  createGraphRelation({
    relation_id: "R04",
    from: "A03",
    to: "topic:bags",
    type: GRAPH_RELATION_TYPES.interestedIn,
    weight: 0.85,
    properties: { source: "high novelty response" },
  }),
  createGraphRelation({
    relation_id: "R05",
    from: "A02",
    to: "T01",
    type: GRAPH_RELATION_TYPES.authored,
    weight: 1,
    properties: { created_tick: 0 },
  }),
  createGraphRelation({
    relation_id: "R06",
    from: "A03",
    to: "T10",
    type: GRAPH_RELATION_TYPES.authored,
    weight: 1,
    properties: { created_tick: 9 },
  }),
  createGraphRelation({
    relation_id: "R07",
    from: "A04",
    to: "T14",
    type: GRAPH_RELATION_TYPES.authored,
    weight: 1,
    properties: { created_tick: 13 },
  }),
  createGraphRelation({
    relation_id: "R08",
    from: "A06",
    to: "topic:pricing",
    type: GRAPH_RELATION_TYPES.alignedWith,
    weight: 0.89,
    properties: { belief: "most-hype-is-overpriced" },
  }),
];

export const SAMPLE_STATE_SNAPSHOT = createStateSnapshot({
  agents: SAMPLE_AGENT_STATES,
  contents: SAMPLE_CONTENT_RECORDS,
  nodes: SAMPLE_GRAPH_NODES,
  relations: SAMPLE_GRAPH_RELATIONS,
});

export const SPRINT1_ROUND_SNAPSHOTS = [
  createSimulationRoundSnapshot({
    round_id: "round-0",
    tick: 0,
    shared_content_ids: ["ext-01", "ext-02", "ext-03"],
    agent_snapshots: [
      createAgentRoundSnapshot({
        snapshot_id: "round-0-S01",
        tick: 0,
        agent_id: "S01",
        exposure_summary: {
          seen_content_ids: ["ext-01", "ext-02"],
          dominant_topic: "care",
        },
        reaction_summary: {
          affect: "moved",
          stance: "quiet_support",
        },
        identity_delta: {
          care_drive: 0.03,
          belonging_drive: 0.02,
        },
        memory_write_summary: {
          recent_memory_count: 2,
          self_narrative_written: true,
        },
        generated_post_ids: ["post-round-0-S01"],
        self_narrative_summary: "Started leaning toward care-heavy interpretation of the same event.",
      }),
      createAgentRoundSnapshot({
        snapshot_id: "round-0-S02",
        tick: 0,
        agent_id: "S02",
        exposure_summary: {
          seen_content_ids: ["ext-01", "ext-03"],
          dominant_topic: "novelty",
        },
        reaction_summary: {
          affect: "energized",
          stance: "signal_seeking",
        },
        identity_delta: {
          novelty_drive: 0.04,
          status_drive: 0.02,
        },
        memory_write_summary: {
          recent_memory_count: 2,
          self_narrative_written: true,
        },
        generated_post_ids: ["post-round-0-S02"],
        self_narrative_summary: "Began reframing the same inputs around signal and freshness.",
      }),
      createAgentRoundSnapshot({
        snapshot_id: "round-0-S03",
        tick: 0,
        agent_id: "S03",
        exposure_summary: {
          seen_content_ids: ["ext-02", "ext-03"],
          dominant_topic: "tradeoffs",
        },
        reaction_summary: {
          affect: "irritated",
          stance: "callout",
        },
        identity_delta: {
          skepticism: 0.03,
          belonging_drive: -0.01,
        },
        memory_write_summary: {
          recent_memory_count: 2,
          self_narrative_written: true,
        },
        generated_post_ids: ["post-round-0-S03"],
        self_narrative_summary: "Turned the same world event into a pricing/tradeoff complaint.",
      }),
    ],
    notes: [
      "Three agents consumed overlapping external inputs but emphasized different meanings.",
      "Each resulting post should be traceable back to distinct reaction and memory updates.",
    ],
  }),
];
